    # ===== znzy.lhyun.net 智能作业 H5（反代到本机 3200）=====
    server {
        listen 80;
        server_name znzy.lhyun.net;

        location = /MP_verify_7PsL7SSTdowwanLf.txt {
            root C:/nginx/html;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name znzy.lhyun.net;

        ssl_certificate     C:/nginx/cert/znzy.lhyun.net.pem;
        ssl_certificate_key C:/nginx/cert/znzy.lhyun.net.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        client_max_body_size 25m;

        location = /MP_verify_7PsL7SSTdowwanLf.txt {
            root C:/nginx/html;
        }

        location / {
            proxy_pass http://127.0.0.1:3200;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_read_timeout 120s;
            proxy_buffering off;
        }
    }
    # ===== znzy.lhyun.net end =====
